name: Nostr
on:
    push: 
      branches:
        - main
    workflow_dispatch:

jobs:
    deno:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        outputs:
            bot_content: ${{ steps.run.outputs.content }}
        steps:
            - name: Setup repo
              uses: actions/checkout@v4
      
            - name: Setup Deno
              uses: denoland/setup-deno@v1
              with:
                deno-version: v1.x
            
            - name: Run Deno
              id: run
            # run: echo "content=$(deno --quiet task bot)" >> $GITHUB_ENV
              run: |
                {
                  echo "content<<EOS"
                  deno --quiet task bot
                  echo EOS
                } >> $GITHUB_OUTPUT
    
    publish:
        needs: deno
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Nostr
              uses: snow-actions/nostr@v1.7.0
              with:
                relays: ${{ vars.NOSTR_RELAYS }}
                private-key: ${{ secrets.NOSTR_PRIVATE_KEY_TEST }}
                content: |
                  ${{ needs.deno.outputs.bot_content }}
            # run: echo "${{ needs.deno.outputs.bot_content }}"
